name: Node.js Package Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: |
          yarn install
      - name: Bootstraping Packages
        run: |
          npx lerna bootstrap

      - name: Building
        run: yarn build
        env:
          CI: false

      - name: Publishing to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
